---
- hosts: database
  become: true
  tasks:
    - name: install mysql-server
      apt: name=mysql-server state=present update-cache=yes

    - name: ensure mysql started
      service: name=mysql state=started enabled=yes