--- 
- hosts: loadbalancer
  become: true
  tasks:    
    - name: install nginx
      apt: name=nginx state=present update_cache=yes

    - name: ensure nginx started
      service: name=nginx state=started enabled=yes




    # - name: Update APT Cache
    #   apt:
    #     update_cache: yes
    #     force_apt_get: yes

    # - name: Remove apt lock file
    #   file:
    #     state: absent
    #     path: "/var/lib/dpkg/lock"

    # - name: Upgrade all packages to the latest version
    #   apt:
    #     name: "*"
    #     state: latest
    #     force_apt_get: yes